### ISSUE TITLE
question about the \kappa in your blog and code

### ISSUE THREAD

**Issue by yzxyzh** [mobiusml/hqq#12]
Hi:

Thanks for your wonderful code and method!

I used to work on compress sensing, but only with L-1 optimization. I'm unfamiliar with the half-quadratic method. I notice that the \kappa is set to 1.01 in your code. If I'm not mistaking, the \kappa acts as a Laplacian penalty argument to me. I thought that if this was the case, the \kappa should be a large parameter, that will guarantee the \beta_t to be infinite after some iterations. 1.01 seems too small for this mission in my point of view? Or the \beta_t does not need to be infinite in half-quadratic optimization?

Thanks for your code again and looking forward to the reply!

**Comment by mobicham** [comment]
Hi @yzxyzh , thank you!
Yes, kappa after multiple iterations will make beta tend to infinity, that's why it should be strictly` kappa > 1`. In practice, when you set kappa close to 1, you get better quality but it requires more iterations since beta will be slowly increasing. Depending on the problem and the outliers level, you might need to set it to higher values. Since in our case iterations are very cheap, we set it to a low values to get the best quality and rely on early stopping to exit the solver. 
You can also set a max beta as the exit strategy for the solver like what they do here: http://www.cse.cuhk.edu.hk/~leojia/papers/L0smooth_Siggraph_Asia2011.pdf

Hope it makes sense!
