### ISSUE TITLE
Why does HQQ not optimize S or both S and Z, but only Z?

### ISSUE THREAD

**Issue by tusiqi1** [mobiusml/hqq#16]
If only optimize S, the S approximation in the round of sp2 is replaced by S(t), and then you go to S(t+1). What's the problem?

Using the same idea, what's wrong with iterating over S and Z if we fix them in order?

**Comment by mobicham** [comment]
Hi, nothing wrong with that. Just to keep things simple in the very first version, we only optimized for **z** because dequantization is a linear operation. You can do the math for **s** following the same idea. In fact, if you go to **optimize.py** and check `optimize_weights_proximal_v2` , we already include scale update via grid search: https://github.com/mobiusml/hqq/blob/master/hqq/core/optimize.py#L109 . It does very slightly improve results for some models. There's also another version with inverse median instead of mean: https://github.com/mobiusml/hqq/blob/master/hqq/core/optimize.py#L7 . The math for this stuff is not in the blogpost and we didn't post about it because the improvement is too tiny to talk about it.
 
Hope it helps!

**Comment by tusiqi1** [comment]
> Hi, nothing wrong with that. Just to keep things simple in the very first version, we only optimized for **z** because dequantization is a linear operation. You can do the math for **s** following the same idea. In fact, if you go to **optimize.py** and check `optimize_weights_proximal_v2` , we already include scale update via grid search: https://github.com/mobiusml/hqq/blob/master/hqq/core/optimize.py#L109 . It does very slightly improve results for some models. There's also another version with inverse median instead of mean: https://github.com/mobiusml/hqq/blob/master/hqq/core/optimize.py#L7 . The math for this stuff is not in the blogpost and we didn't post about it because the improvement is too tiny to talk about it.
> 
> Hope it helps!

Thanks for your answer which solved my confusion very effectively!

**Comment by shadowpa0327** [comment]
Hi @mobicham, thanks first for the explanation. 
I am wondering that how the HQQ work on the symmetric quantization scheme. 
Is it possible to rewritten the sub-problem 2 to optimize the scales instead?

**Comment by mobicham** [comment]
@shadowpa0327 if there's no zero-point and you use the l1-norm, the solution is simply the median over the group-size axis. 
imo quantization doesn't work that well with LLMs at low bits without the zero-point, that's we optimize mainly for z (because z acts like an error correction term). We actually did some math to re-write the dequantization step in a way that would benefit from faster matmul (when W_q is 1-bit for example), we will post that soon as a blog-post, that's related a bit to the symmetric quantization use-case.
