### ISSUE TITLE
Collaboration: Unsloth + HQQ

### ISSUE THREAD

**Issue by danielhanchen** [mobiusml/hqq#8]
Hey HQQ team! Happy New Year!

I actually found out about HQQ from some Reddit posts about Mixtral - and had a look at https://github.com/mobiusml/hqq/issues/2 which was super insightful! Quantizing the attention layers in 4bit, and the MLP layers in 2bit is ingenious!

Also I compared BnB and HQQ's quantizations and it does seem HQQ is generally always better on the reconstruction error between the quantized and non quantized weight matrices.

I forgot to intro myself, but I'm the maintainer of Unsloth. We made QLoRA 2.2x faster and use 62% less memory!

I was thinking of supporting HQQ since it looks like a fabulous replacement to BnB's nf4, and HQQ also works for 3 and 2 bit quantization with 0 data calibration - so that's super sick!

It'll be cool if we can collaborate in anyway!

**Comment by mobicham** [comment]
Hi @danielhanchen ! Happy new year and congrats on the **Unsloth** 🦥 work, looks very cool !

Regarding HQQ + LoRA, I wanted to kick off the conversation by first having a working version. I just pushed it now and it looks like it's working fine: https://github.com/mobiusml/hqq/blob/master/examples/lora/train_hqq_lora_example.py
*Quick* comparison between HQQ and BNB below on a subset of OpenAssistant using a small sequence length of 256. (Base) means it's the quantized model before training. Obviously we would need a more detailed benchmark.

| Method   |     Train GPU MEM      |  Train Time | PPL (lr constant) | PPL (lr linear) 
|----------|:-------------:|------:|------:|------:|
| BNB (Base) |  - | - | 8.570 | -
| HQQ (Base) |  - | - | 8.094 | -
| BNB + LoRA|  6.90 GB | 32 mins | 6.770 | 5.981
| HQQ + LoRA|    6.95 GB   |  35 mins | 6.246 |  5.689

This is using bfloat16 for the LoRA weights which is quite slower than float on the Titan RTX. The speed is actually not bad given that HQQ is a pure Pytorch implementation while BNB uses optimized kernels. 

There's an endless list of things that could be improved, here's a subset, would love to hear your feedback:

- The main challenge with quantization + LoRA is avoiding the dequantized weights being cached in the context. So the backward pass should be rewritten to force weight dequantization again. Without this, the memory explodes during training. 
I have experimented with different versions and found that the most efficient way so far is to pass the `matmul` op: https://github.com/mobiusml/hqq/blob/master/hqq/core/quantize.py#L175 . This is because Torch Dynamo breaks when it tries to compile the backward pass. But since the `matmul` op is used in both the forward and backward pass, it can be compiled separately and passed as an argument to autograd. I think this part alone can be improved.

- Since the quantization logic of HQQ is still under development (we are currently working on a new version which is significantly better but the logic is different), we use a pure Pytorch implementation and rely on Torch Dynamo to speed-up inference. This also allows the open-source community to use HQQ on old devices, which is not possible with some quantization methods that require devices compatible with their Triton kernels. However, it will be great to have a Triton backend that the user can choose to speed-up inference on newer GPUs. Luckily, the folks that did the Mixtral-Offloading work already adapted HQQ for Triton, so that can be re-used: https://github.com/dvmazur/mixtral-offloading/blob/master/src/custom_layers.py#L16 
Since the quantization is linear like GPTQ, their Triton kernels can be re-used after changing the bitpacking logic and a few other things. The Pytorch folks are also working on a version for 4-bit, but I had some issues running it: https://github.com/pytorch-labs/ao/blob/main/torchao/quantization/subclass.py#L296.
In terms of LoRA training, the Triton kernel could be used for inference, but it doesn't look like it can be used in the backward pass because the dequantized weights should not be transposed. One way would be to do matmul with the identity matrix to get the dequantized weights and then do the matmul in the backward pass, but that could be slower than just doing it in Pytorch Dynamo. 

- The base models from Hugging Face are quite slow and there is a lot of room for improvement: merge QKV / MLP layers, faster attention, better layernorm kernels, ... 

- The are many improvements that we plan to add to HQQ as well. For example, passing the compute type to avoid recasting. By default, the model loads the weights in float16, but if the LoRA weights are bfloat16, it needs to cast them back and forth.

**Comment by danielhanchen** [comment]
@mobicham Love the LoRA example and damn the perplexity reduction is sick!!!

1. LoRA dequantization + `torch.compile`: Interestingly I found `torch.cuda.make_graph_callables` (I'm sure I wrote that wrong) could be useful - a full graph capture might be problematic, as memory usage can sometimes explode. I also found CUDA Graphs to approx save 10% max time, so maybe only do the dequant step with `torch.compile` then a normal `matmul` sounds best. Another approach is to write HQQ in Triton!
2. Ye saw the Triton kernels for Mixtral Offloading! I think they directly made a `gemm` kernel ( or was it just `gemv`? ) Also saw Pytorch's one - ye only 4 and 8bit I think was it - I liked HQQ's 4, 3, 2 bit support!!! OOO a NEW version! :) If you need any help on it - more than happy to chip in! I can also write some Triton kernels as well like for Unsloth for the dequantization step for training, and a `gemv` kernel for inference :)
3. Yeee Unsloth!!
4. Ye found that issue as well for `bitsandbytes` - I also fixed that for Unsloth, but memory movement I found to be around a 10% performance hit during training.

**Comment by mobicham** [comment]
Thanks for your answer @danielhanchen !

1. So I did the test and it seems that it's about the same. Maybe it will depend on the torch.compile settings as well, haven't played much with that. 

2. Regarding the Triton kernels, I have played with Triton a bit in the past and had mixed results. I tried the kernels from https://github.com/dvmazur/mixtral-offloading/blob/master/src/custom_layers.py#L16 on a Titan RTX and they are more than 6x slower than torch.compile(). They also take much more memory: 

| Framework           | PPL      | Speed      | Memory   | Memory (prediction @ 1024) |
|---------------------|----------|------------|----------|---------------------------|
| PYTORCH_COMPILE     | 5.3013   | 0.304 sec  | 4.409 GB | 5.351 GB                  |
| Triton              | 5.3013   | 1.987 sec  | 7.721 GB | 8.54 GB                   |

One approach could be to take the generated Triton kernels from torch.compile() and improve them. Or maybe reusing GPTQ kernels after changing the bitpacking logic, but they were not actually that fast based on the tests I did a couple of months ago. 
I think for the moment torch.compile is working just fine.
If you have ideas on how to make it faster, you are more than welcome to take a stab at it! I also made a placeholder for Aten backend that could be useful for adding CUDA kernels: https://github.com/mobiusml/hqq/tree/master/hqq/kernels 
I think though that the actual speed-up will come from the model architecture (merging layers, etc.). For example, VLLM + HQQ is about 5x faster than HF + HQQ. However, VLLM is for inference only as far as I know.    

3. I tried Unsloth today. After loading the model I can see that the q,k,v layers (and mlp) are still separated, I couldn't find the part where it patches the qkv layers to merge them. The inference speed was also the same as the original model. Maybe I am missing some patching step ?

4. Oh damn, 10% is a lot for something like that! Will definitely add that then

**Comment by mobicham** [comment]
Adding also this note on the AutoAWQ Cuda kernels: 
https://github.com/mobiusml/hqq/issues/11#issuecomment-1883054449

**Comment by danielhanchen** [comment]
@mobicham I'll reply to everything tomorrow!!

**Comment by danielhanchen** [comment]
@mobicham Sorry for the delayed response - had a lot on my plate so just got to this!

I'll also interact in the other Github issues! :)

1. Ye `torch.compile` can be noticeably faster than custom Triton kernels esp if it's not written properly. I have not yet investigated the offloading mixtral repo, but will plan to check them out as well. I can approximately see they did some `gemv` kernels or maybe `gemm` kernels, albeit it doesn't look optimized.
2. Ye! Agreed taking the generated triton kernels and optimizing on top of them - that's actually quite an ingenious idea!
3. Ohh noo so Unsloth only makes LoRA finetuning faster - inference is the same speed as HF. I was planning to wrap `model.generate` with `torch.compile` as a temporary solution. Ye I found combining `Q, K, V` into 1 layer actually hurts VRAM usage a lot, and also the time reductions from that are around 1% or so. I decided to leave all 3 linear layers as separate entities. Also for GQA, since K and V are expanded, one has to split Q, K, V up into 3, but then it needs to be Fortran contiguous, or else the GQA will be somewhat slower due to incorrect strides.
4. Ye! 10% is a bunch!

I'll be playing around with HQQ more in the coming weeks - hopefully we can collaborate on anything together!

**Comment by mobicham** [comment]
Thanks @danielhanchen !
- I didn't get a useful response so far about caching the compiled kernels, here's the discussion: https://github.com/pytorch/pytorch/issues/117045#issuecomment-1883972736 
- Oh I see, it will for sure introduce extra memory because for dequantization it will have to store all 3 matrices in fp16 at some point. I was also curious about how that would work with KV caching and that's how they do it in VLLM: https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/llama.py#L151 , so basically they do matmul with merged QKV and they add the KV cache later.
Regarding applying `torch.compile` on the model, it is actually faster but it uses more VRAM. That's why in HQQ we compile the function not the model!

Great, take your time, I will also be busy in the coming weeks !

**Comment by danielhanchen** [comment]
@mobicham 

1. OOO interesting convo - I'll take a look!
2. Ye I can see it's merged as well! They do do splitting though:
```
        q, k, v = qkv.split([self.q_size, self.kv_size, self.kv_size], dim=-1)
        q, k = self.rotary_emb(positions, q, k)
        k_cache, v_cache = kv_cache
        attn_output = self.attn(q, k, v, k_cache, v_cache, input_metadata)
        output, _ = self.o_proj(attn_output)
```
Technically merging QKV does improve performance esp during inference and if the bsz is small say 1. For training, VRAM is more important, and I benchmarking combined QKV and splitted QKV - there is a performance hit of around 0.3% ish, so I thought the VRAM benefits were more important.

3. Yee I too also found `torch.compile` to suck up more memory - in fact that's one of the main reasons I rewrote all kernels manually in Triton - `torch.compile` seems to really like to eat up loads of VRAM biscuits!!

Cool! I'll probably see if I have some more timr porting over HQQ to Unsloth - and I'll share my findings / Triton code etc as well!

**Comment by mobicham** [comment]
2. Yeah! I think if the QKV tensor is contiguous, splitting should not involve a copy though. Yesit will increase memory, also for dequantization which happens in both the forward and backward pass !

3. I see, the trick is to always compile only a few functions not the model! With torch compiling the matmul or dequantization step in HQQ, there's almost no VRAM increase!

Great 🙌! Meanwhile, I need to add a couple of other features as well, like select device and compute dtype, etc. I will probably add that in 1 or 2 weeks.

**Comment by danielhanchen** [comment]
@mobicham
1. Agreed yep! If QKV is contiguous no need to worry :) But ye just the extra VRAM usage :)
2. Agreed on compiling only certain functions :) I guess the main premise was for a simple wrapper for `torch.compile` on all functions :) I guess the Pytorch team needs to make a system to only compile some parts automatically

Cool!

**Comment by mobicham** [comment]
@danielhanchen

**Comment by danielhanchen** [comment]
@mobicham Hey! So sorry just saw this!! Oh cool - fantastic work!! :) I'll work to add HQQ in the following weeks :))
